name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  tests_and_sonar_scan:
    name: Run Tests and SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install

      - name: Run unit & integration tests
        run: npm run test:ci

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
  e2e_tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install

      - name: Install Docker Compose
        run: sudo apt-get install -y docker-compose

      - name: Build and Run container
        run: docker-compose up --build --detach

      - name: Wait for the API to be ready
        run: |
          for i in `seq 1 10`; do
            nc -z localhost 3000 && echo Success && exit 0
            echo "Waiting for API to be ready..."
            sleep 5
          done
          echo "Failed to connect to API on port 3000"
          exit 1

      - name: Run E2E tests
        run: npm run test:e2e

      - name: Stop and remove containers
        if: always()
        run: docker-compose down
